baseUrl=https://the-internet.herokuapp.com
webFormUrl=https://www.selenium.dev/selenium/web/web-form.html
alertsUrl=https://www.selenium.dev/selenium/web/alerts.html
browser=chrome
headless=false
explicitWait=10
